/*
 * QMI and PADS_QSPI register definitions for boot stage 2
 */
#ifndef _BOOT_STAGE2_REGS_H
#define _BOOT_STAGE2_REGS_H

// Address map
#define REG_ALIAS_CLR_BITS      0x3000

// QMI base offsets
#define QMI_DIRECT_CSR_OFFSET           0x00
#define QMI_DIRECT_TX_OFFSET            0x04
#define QMI_DIRECT_RX_OFFSET            0x08
#define QMI_M0_TIMING_OFFSET            0x0c
#define QMI_M0_RCMD_OFFSET              0x10
#define QMI_M0_RFMT_OFFSET              0x14

// QMI bits
#define QMI_DIRECT_CSR_CLKDIV_LSB       8
#define QMI_DIRECT_CSR_CLKDIV_BITS      0x0000ff00
#define QMI_DIRECT_CSR_EN_BITS          0x00000001
#define QMI_DIRECT_CSR_AUTO_CS0N_BITS   0x00000004
#define QMI_DIRECT_CSR_BUSY_BITS        0x00010000
#define QMI_DIRECT_CSR_BUSY_LSB         16

#define QMI_M0_TIMING_COOLDOWN_LSB      24
#define QMI_M0_TIMING_RXDELAY_LSB       16
#define QMI_M0_TIMING_RXDELAY_BITS      0x00070000
#define QMI_M0_TIMING_CLKDIV_LSB        0
#define QMI_M0_TIMING_CLKDIV_BITS       0x000000ff

#define QMI_M0_RCMD_PREFIX_LSB          0
#define QMI_M0_RCMD_SUFFIX_LSB          16

#define QMI_M0_RFMT_PREFIX_WIDTH_LSB    0
#define QMI_M0_RFMT_PREFIX_WIDTH_VALUE_S 0
#define QMI_M0_RFMT_ADDR_WIDTH_LSB      4
#define QMI_M0_RFMT_ADDR_WIDTH_VALUE_Q  2
#define QMI_M0_RFMT_SUFFIX_WIDTH_LSB    6
#define QMI_M0_RFMT_SUFFIX_WIDTH_VALUE_Q 2
#define QMI_M0_RFMT_DUMMY_WIDTH_LSB     8
#define QMI_M0_RFMT_DUMMY_WIDTH_VALUE_Q 2
#define QMI_M0_RFMT_DATA_WIDTH_LSB      10
#define QMI_M0_RFMT_DATA_WIDTH_VALUE_Q  2
#define QMI_M0_RFMT_PREFIX_LEN_LSB      12
#define QMI_M0_RFMT_PREFIX_LEN_VALUE_8  1
#define QMI_M0_RFMT_SUFFIX_LEN_LSB      14
#define QMI_M0_RFMT_SUFFIX_LEN_VALUE_8  1
#define QMI_M0_RFMT_DUMMY_LEN_LSB       16
#define QMI_M0_RFMT_DUMMY_LEN_BITS      0x00ff0000
#define QMI_M0_RFMT_PREFIX_LEN_BITS     0x00003000

// PADS_QSPI offsets
#define PADS_QSPI_GPIO_QSPI_SCLK_OFFSET     0x04
#define PADS_QSPI_GPIO_QSPI_SD0_OFFSET      0x08
#define PADS_QSPI_GPIO_QSPI_SD1_OFFSET      0x0c
#define PADS_QSPI_GPIO_QSPI_SD2_OFFSET      0x10
#define PADS_QSPI_GPIO_QSPI_SD3_OFFSET      0x14

#define PADS_QSPI_GPIO_QSPI_SCLK_DRIVE_LSB  0
#define PADS_QSPI_GPIO_QSPI_SCLK_SLEWFAST_BITS  0x00000001
#define PADS_QSPI_GPIO_QSPI_SD0_SCHMITT_BITS    0x00000002

#endif // _BOOT_STAGE2_REGS_H
