/*
 * Pin configuration definitions
 * This file contains the actual initialization data for pin arrays
 */

#include "pins.h"

// Pin function map - defines what function each GPIO is configured for
uint8_t global_pin_func_map[48] = {
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL,
    GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL, GPIO_FUNC_NULL
};

// Pull-up/down configuration for each GPIO
uint8_t global_pin_pullup[48] = {
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP,
    GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP, GPIO_PULL_UP
};

// Direction configuration for each GPIO
uint8_t global_pin_direction[48] = {
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT,
    GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT, GPIO_DIR_OUT
};
